disaster_project/disaster_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),  # This is the line that I added
]

disaster_project/user/urls.py
from django.urls import path
from . import views


app_name = "user"

urlpatterns = [
    path('', views.request_help_view, name='index'),
    path('login', views.login_view, name='login'),
    path('help_need', views.help_need_view, name='help_need'),
    path('help_map', views.help_map, name='help_map'),
    path('volunteer', views.volunteer_view, name='volunteer'),
    
    path('register', views.register_view, name='register'),
    path("logout", views.logout_view, name="logout"),
    path("activate/<str:uidb64>/<str:token>", views.activate, name='activate'),
    path('first_aid', views.firstaid_view, name='first_aid'),
    path('profile', views.profile_view, name='profile'),
    path('admin', views.admin_view, name='admin'),
    path('userslist', views.userslist_view, name='userslist'),
    path('food_form', views.food_form_view, name='food_form'),
    path('shelter_form', views.shelter_form_view, name='shelter_form'),
    path('medical_form', views.medical_form_view, name='medical_form'),
    path('hygiene_form', views.hygiene_form_view, name='hygiene_form'),
    path('clothes_form', views.clothes_form_view, name='clothes_form'),
    path('heaters_form', views.heaters_form_view, name='heaters_form'),
    path('update-quantity/<int:pk>/', views.update_quantity, name='update_quantity'),
    path('helped_archive', views.helped_archive, name='helped_archive'),
    path('my_requests', views.my_requests, name='my_requests'),
    path('delete_request/<int:pk>/', views.delete_request, name='delete_request'),
    path('about_us', views.aboutus_view, name='about_us'),
    path('hospitals', views.hospital_locations_view, name='hospitals'),
    path('nearby-hospitals', views.nearby_hospitals, name='nearby_hospitals'),
    path('manage_help_post/', views.manage_help_post_view, name='manage_help_post'),
    path('delete_help_post/', views.delete_help_post_view, name='delete_help_post'),
    path('hide_help_post/', views.hide_help_post_view, name='hide_help_post'),
    path('show_help_post/', views.show_help_post_view, name='show_help_post'),
    path('statistics/', views.statistics_view, name='statistics'),


]

disaster_project/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from .models import HelpNeed, ClothesRequest

User = get_user_model()


# Create your forms here.
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class HelpNeedForm(forms.ModelForm):
    lat = forms.CharField(widget=forms.HiddenInput(), initial='0')
    lon = forms.CharField(widget=forms.HiddenInput(), initial='0')
    address = forms.CharField(required=True)

    class Meta:
        model = HelpNeed
        fields = ("first_name","last_name", "phone", "address", "lat", "lon")




class ReadyForm(forms.ModelForm):
    lat = forms.CharField(widget=forms.HiddenInput(), initial='0')
    lon = forms.CharField(widget=forms.HiddenInput(), initial='0')
    address = forms.CharField(required=True)
    help_class = forms.CharField(max_length=20, widget=forms.HiddenInput())
    user_type = forms.CharField(max_length=20, widget=forms.HiddenInput())
    class Meta:
        model = HelpNeed
        fields = ("first_name","last_name", "phone", "address","lat", "lon", "quantity", "help_class", "user_type")

class ClothesRequestForm(forms.ModelForm):
    lat = forms.CharField(widget=forms.HiddenInput(), initial='0')
    lon = forms.CharField(widget=forms.HiddenInput(), initial='0')
    address = forms.CharField(required=True)
    help_class = forms.CharField(max_length=20, widget=forms.HiddenInput())
    user_type = forms.CharField(max_length=20, widget=forms.HiddenInput())

    class Meta:
        model = ClothesRequest
        fields = ("first_name","last_name", "phone", "address","lat", "lon", "quantity", "help_class", "user_type", "category", "size")

class ProfileForm(forms.ModelForm):
    last_name = forms.CharField(required=False, disabled=True)                         
    username = forms.CharField(required=False, disabled=True)
    email = forms.CharField(required=False, disabled=True)
    date_joined = forms.CharField(required=False, disabled=True)
    phone =  forms.IntegerField (required=False)
    lat = forms.CharField(widget=forms.HiddenInput(), initial='0')
    lon = forms.CharField(widget=forms.HiddenInput(), initial='0')
    address = forms.CharField(required=True)
    class Meta:
        model = User
        fields = ('first_name','last_name','username', 'email', 'phone', 'address','date_joined')
        help_texts = {
            'username': None,
        }
        
class VolunteerRequestForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.HiddenInput())
    last_name = forms.CharField(widget=forms.HiddenInput())
    phone = forms.CharField(widget=forms.HiddenInput())
    lat = forms.CharField(widget=forms.HiddenInput(), initial='0')
    lon = forms.CharField(widget=forms.HiddenInput(), initial='0')
    address = forms.CharField(required=True)
    user_type = forms.CharField(max_length=20, widget=forms.HiddenInput())
    help_class = forms.CharField(max_length=20, widget=forms.HiddenInput())

    class Meta:
        model = HelpNeed
        fields = ("first_name","last_name", "address", "phone","lat", "lon", "quantity", "help_class", "user_type", "volunteer")

        widgets = {
            'volunteer': forms.HiddenInput(),
        }

class VolunteerClothesRequestForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.HiddenInput())
    last_name = forms.CharField(widget=forms.HiddenInput())
    phone = forms.CharField(widget=forms.HiddenInput())
    lat = forms.CharField(widget=forms.HiddenInput(), initial='0')
    lon = forms.CharField(widget=forms.HiddenInput(), initial='0')
    address = forms.CharField(required=True)
    user_type = forms.CharField(max_length=20, widget=forms.HiddenInput())
    help_class = forms.CharField(max_length=20, widget=forms.HiddenInput())


    class Meta:
        model = ClothesRequest
        fields = (
        "first_name", "last_name", "phone", "address", "lat", "lon", "quantity", "help_class", "user_type", "category",
        "size", "volunteer")

        widgets = {
            'volunteer': forms.HiddenInput(),
        }

disaster_project/user/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.template import loader
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from .models import HelpNeed,  HelpNeedHelper, Hospitals
from .models import HelpNeed, HelpNeedHelper, User
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.contrib.auth import get_user_model
from .forms import NewUserForm, HelpNeedForm, ProfileForm, ReadyForm, \
    VolunteerRequestForm, ClothesRequestForm, VolunteerClothesRequestForm
from django.http import JsonResponse
from pymongo import MongoClient
from django.core.paginator import Paginator
import folium
from folium.plugins import FastMarkerCluster
from math import radians, sin, cos, sqrt, atan2
import logging
import uuid
from django.db.models import Max, Min



logger = logging.getLogger(__name__)
def index(request):
    template = loader.get_template('user/index.html')
    context = {}
    if not request.user.is_authenticated:
        context['variable'] = "you are not allowed"
        context['logged'] = False
    else:
        context['variable'] = "you are allowed"
        context['logged'] = True

    return HttpResponse(template.render(context, request))


def logout_view(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("user:index")


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            admin = "admin"
            user = authenticate(username=username, password=password)

            if username == admin:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("user:admin")
            elif user != None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("user:volunteer")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="user/login.html", context={"login_form": form})


def register_view(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            if settings.DEVELOPMENT != 'True':
                user.is_active = False
            user.save()

            current_site = get_current_site(request)
            mail_subject = 'Activation link has been sent to your email id'
            message = render_to_string('user/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            if settings.DEVELOPMENT != 'True':
                email.send()
            return render(request, 'user/Email.html',
                          {'msg': 'Please confirm your email address to complete the registration'})
    else:
        from django.urls import reverse
        form = NewUserForm()
    return render(request=request, template_name="user/register.html", context={"register_form": form})


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, 'user/Email.html',
                      {'msg': 'Thank you for your email confirmation. Now you can login your account.'})
    else:
        return render(request, 'user/Email.html', {'msg': 'Activation link is invalid!'})
"""index"""
def help_need_view(request):
    if request.method == "POST":
        form = HelpNeedForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, f"Your help request has been received.")
            return redirect("user:index")
        else:
            messages.error(request, "Name and phone are mandatory.")
    form = HelpNeedForm()
    return render(request=request, template_name="user/index.html", context={"help_need_form": form})

def help_map(request):
    needs = HelpNeed.objects.all()
    map = folium.Map(location=[38.9637, 35.2433], zoom_start=6)
    marker_cluster = FastMarkerCluster(
        data=list(
            zip([need.lat for need in needs], [need.lon for need in needs])))

    locations = [(need.lat, need.lon) for need in needs]
    popups = [(need.first_name, need.last_name, need.phone, need.help_class) for need in needs]

    for location, popup in zip(locations, popups):
        folium.Marker(location, popup=popup).add_to(marker_cluster)

    marker_cluster.add_to(map)

    needs = map._repr_html_()

    return render(request=request, template_name="user/help_map.html", context={"needs": needs})


def help_need_list(request):
    needs = HelpNeed.objects.all()
    return render(request=request, template_name="user/help_need_list.html", context={"needs": needs})


def volunteer_view(request):
    needs = HelpNeed.objects.filter(quantity__gt=0).order_by('-created_at').exclude(volunteer=request.user)
    paginator = Paginator(needs, 10) # Change 10 to the number of items you want per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request=request, template_name="user/volunteer.html", context={"needs": page_obj})

def firstaid_view(request):
    return render(request=request, template_name="user/firstaid.html")

def profile_view(request):
    form = ProfileForm(request.POST or None, instance=request.user)
    if request.method == 'POST':
        if form.is_valid():
         form.save()
    else:
        form = ProfileForm(request.POST or None, instance=request.user)
    return render(request=request, template_name="user/profile.html", context={"profile_form": form})



@login_required
def admin_view(request):
     return render(request=request, template_name="user/admin.html")


@login_required
def userslist_view(request):
    users = User.objects.all()
    paginator = Paginator(users, 10) # Show 10 users per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request=request, template_name="user/userslist.html", context={"page_obj": page_obj})


def food_form_view(request):
    if request.user.is_authenticated:
        form = VolunteerRequestForm(request.POST or None, initial={'help_class': "food", 'user_type': "volunteer", 'volunteer': request.user})
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                messages.info(request, f"Volunteer, Your help request has been received.")
                form = VolunteerRequestForm(request.POST or None, initial={'help_class': "food", 'user_type': "volunteer", 'volunteer': request.user})
        else:
            form = VolunteerRequestForm(request.POST or None, initial={'help_class': "food", 'user_type': "volunteer", 'volunteer': request.user})
        return render(request=request, template_name="user/volunteer_requests.html", context={"help_need_form": form})
    else:
        form = ReadyForm(request.POST or None,initial={'help_class': "food", 'user_type': "victim"})
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                messages.info(request, f"Your help request has been received.")
                return redirect("user:food_form")
        else:
            form = ReadyForm(request.POST or None,initial={'help_class': "food", 'user_type':"victim"})

        return render(request=request, template_name="user/food_form.html", context={"ready_form":form})
def shelter_form_view(request):
    if request.user.is_authenticated:
        form = VolunteerRequestForm(request.POST or None, initial={'help_class': "shelter", 'user_type': "volunteer", 'volunteer_requests': request.user})
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                messages.info(request, f"Volunteer, Your help request has been received.")
                form = VolunteerRequestForm(request.POST or None, initial={'help_class': "shelter", 'user_type': "volunteer", 'volunteer': request.user})

        else:
            form = VolunteerRequestForm(request.POST or None, initial={'help_class': "shelter", 'user_type': "volunteer", 'volunteer': request.user})
        return render(request=request, template_name="user/volunteer_requests.html", context={"help_need_form": form})
    else:
        form = ReadyForm(request.POST or None, initial={'help_class': "shelter", 'user_type': "victim"})
        if request.method == 'POST':

disaster_project/user/templates/user/Email.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% block content %}
 <div class="content-section col-md-8 col-md-offset-2">
	<h2>{{msg}}</h2>
	<a href="{% url 'user:login' %}" target="_blank" rel="noopener noreferrer">Login</a>
</div>
{% endblock content %}

disaster_project/user/templates/user/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},welcome {{ user.first_name }}
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}
{% endautoescape %}

disaster_project/user/templates/user/admin.html
{% extends "user/base.html" %}
{% load custom_tags %}

{% block title %}
    <title>ADMIN Hompage</title>
{% endblock %}


{% block content %}
<style>
.jumbotron.jumbotron-fluid{
    text-align: center;
    background: none;
}
.lead{
    font-weight: 350;
    display: inline-grid;
    padding: 25px 30px 25px 30px;
}
</style>

<head>

    <!-- style css -->
    <link rel="stylesheet"  href="/static/user/admin-css/style.css">
    
    <!-- Tweaks for older IEs-->
</head>

{% load crispy_forms_tags %}

    <div class="section1light">
         <div class="row">
            <div class="col-sm-12">
                <div class="jumbotron jumbotron-fluid">
                  <div class="container">
                    
                  </div>
                </div>
            </div>
        </div>
   </div>


   <div class="container">
    <div class="box_section">
       <div class="online_box">
          <div class="online_box_left">
             <a href="/userslist"><div class="online_box_main">
                <div class="box_left">
                   <div class="right_arrow"><i class="fa fa-arrow-right"></i></div>
                </div>
                <div class="box_right">
                   <p class="book_text">View</p>
                   <h4 class="appoinment_text">User List</h4>
                </div>
             </div></a>
          </div>
          <div class="online_box_left">
             <a href="/manage_help_post"><div class="online_box_main">
                <div class="box_left">
                   <div class="right_arrow"><i class="fa fa-arrow-right"></i></div>
                </div>
                <div class="box_right">
                   <p class="book_text">Manage</p>
                   <h4 class="appoinment_text">Help Post</h4>
                </div>
             </div></a>
          </div>
          <div class="online_box_left">
            <a href="/statistics"><div class="online_box_main">
               <div class="box_left">
                  <div class="right_arrow"><i class="fa fa-arrow-right"></i></div>
               </div>
               <div class="box_right">
                  <p class="book_text">Manage</p>
                  <h4 class="appoinment_text">Statistics</h4>
               </div>
            </div></a>
         </div>
       </div>
    </div>
 </div>

{% endblock %}

disaster_project/user/templates/user/help_need_list.html
{% extends "./base.html" %}
{% load custom_tags %}
{% block content %}

<div class="content-section col-md-8 col-md-offset-2">
  <div class="list-group">
      {% paginate needs by 10 as page_obj %}
         {% for need in needs %}
            <a href="#" class="list-group-item list-group-item-action" aria-current="true">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"> {{ need.name }} </h5>
            <small>{{ need.created_at | prettydate }}</small>
          </div>
          <p class="mb-1">{{ need.phone }}</p>
          <small> {{ need.address }}</small>
            </a>
        {% endfor %}
        
     {% endpaginate %}
  </div>

</div>
{% endblock content %}

disaster_project/user/templates/user/manage_help_post.html
{% extends "user/base.html" %}
{% load custom_tags %}

{% block title %}
<title>ADMIN Manage Help Post</title>
{% endblock %}


{% block content %}
{% csrf_token %} 
<style>
  .jumbotron.jumbotron-fluid {
    text-align: center;
    background: none;
  }

  .lead {
    font-weight: 350;
    display: inline-grid;
    padding: 25px 30px 25px 30px;
  }

  .submitform {
    margin: auto;
    display: block;
    padding: 10px;
  }

  .btnclass {
    < !-- height: 200px;
    -->< !-- width: 200px;
    -->background-color: yellowgreen;
    position: relative;
  }

  .alist:hover .groupbtn {
    display: block;
  }

  .groupbtn {
    display: none;
    position: absolute;
    top: 5px;
    right: 5px;
  }

  .red-button {
  background-color: red;
}

  table {
    border-collapse: collapse;
    width: 100%;
    max-width: 1200px;
    margin: 0 auto;
    font-size: 14px;
    text-align: center;
  }

  th {
    background-color: #abd4c6;
    border: 1px solid #ddd;
    padding: 8px;
    text-transform: uppercase;
  }

  td {
    border: 1px solid #ddd;
    padding: 8px;
  }
  .hidden-row {
    display: none;
  }
</style>


<head>
  <link rel="stylesheet" type="text/css" href="/static/user/admin-css/style.css">
  <link href="https://fonts.googleapis.com/css2?family=Sen:wght@400;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
</head>

{% load crispy_forms_tags %}

<div class="section1light">
  <div class="row">
    <div class="col-sm-12">
      <div class="jumbotron jumbotron-fluid">
        <div class="container">

        </div>
      </div>
    </div>
  </div>
</div>
 


<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p class="lead 1" style="text-align:left">Help List</p>
      <button id="show-button" class="btn btn-secondary">Show Hidden</button>
      <table>
        <tr>
            <th></th>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Address</th>
            <th>Help Class</th>
            <th>Quantity</th>
            <th>Created At</th>
        </tr>
        {% for need in page_obj %}
            <tr id="row-{{ need.helpneedid }}" class="row-item {% if need.hidden %}hidden-row{% endif %}">
                <form action="{% url 'user:delete_help_post' %}" method="post">
                    {% csrf_token %}
                    <td><input type="checkbox" name="selected_ids" value="{{ need.helpneedid }}"></td>
                    <td>{{ need.id }}</td>
                    <td>{{ need.first_name }}</td>
                    <td>{{ need.last_name }}</td>
                    <td>{{ need.address }}</td>
                    <td>{{ need.help_class }}</td>
                    <td>{{ need.quantity }}</td>
                    <td>{{ need.created_at | prettydate }}</td>
                </form>
                <td><button class="btn btn-secondary hide-button" data-row-id="{{ need.helpneedid }}">Hide</button></td>
            </tr>
        {% endfor %}
    </table>
    
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">« first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current-page">{{ page_obj.number }}</span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last »</a>
            {% endif %}
        </span>
    </div>
    
    
      <form action="{% url 'user:delete_help_post' %}" method="post" id="delete-selected-form">
        {% csrf_token %}
        <input type="hidden" name="selected_ids" id="selected-ids-input">
        <button type="button" class="btn btn-danger" id="delete-selected-button">Delete Selected</button>
       </form>
       
    </div>

  </div>
</div>



<script>

const hideButtons = document.querySelectorAll('.hide-button');


hideButtons.forEach((button) => {
 button.addEventListener('click', () => {
 
 const rowId = button.getAttribute('data-row-id');

 
 $.ajax({
 url: '{% url 'user:hide_help_post' %}',
 method: 'POST',
 data: {
 csrfmiddlewaretoken: csrfToken,
 helpneedid: rowId,
 },
 success: (data) => {
 
 
 const row = document.getElementById(`row-${rowId}`);
 row.style.display = 'none';
 },
 error: (jqXHR, textStatus, errorThrown) => {
 console.error(`Error hiding record: ${errorThrown}`);
 },
 });
 });
});
</script>

<script>
  
const showButton = document.getElementById('show-button');


showButton.addEventListener('click', () => {
 
 const hiddenRows = document.querySelectorAll('.row-item');

 
 const hiddenIds = Array.from(hiddenRows).map((row) => row.getAttribute('id').replace('row-', ''));

 
 $.ajax({
 url: '{% url 'user:show_help_post' %}',
 method: 'POST',
 data: {
 csrfmiddlewaretoken: csrfToken,
 helpneedids: hiddenIds,
 },
 success: (data) => {
  console.log('AJAX request succeeded');
 
 
 hiddenRows.forEach((row) => {
  console.log(`Showing row: ${row.id}`);
  row.classList.remove('hidden-row');
 });
 },
 error: (jqXHR, textStatus, errorThrown) => {
 
 
 console.error(`Error showing records: ${errorThrown}`);
 },
 });
});
</script>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<script>
  
  const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
  
  
  const deleteSelectedButton = document.getElementById('delete-selected-button');
  
  
  deleteSelectedButton.addEventListener('click', () => {
   
   const selectedCheckboxes = document.querySelectorAll('input[name="selected_ids"]:checked');
  
   
   const selectedIds = Array.from(selectedCheckboxes).map((checkbox) => checkbox.value);
  
   
   $.ajax({
   url: '{% url 'user:delete_help_post' %}',
   method: 'POST',
   data: {
   csrfmiddlewaretoken: csrfToken,
   selected_ids: selectedIds,
   },
   success: (data) => {
   
   
   selectedIds.forEach((id) => {
   const row = document.getElementById(`row-${id}`);
   row.remove();
   });
   },
   error: (jqXHR, textStatus, errorThrown) => {
   
   console.error(`Error deleting objects: ${errorThrown}`);
   },
   });
  });
  </script>
  
  

{% endblock %}

disaster_project/user/templates/user/my_requests.html
<!DOCTYPE html>
{% extends "user/base.html" %}
{% load custom_tags %}
{% load crispy_forms_tags %}


<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css">

    <meta charset="UTF-8">
{% block title %}
    <title>My Requests</title>
{% endblock %}



</head>
{% block content %}


<style>
.lead{
    font-weight: 350;
    display: inline-grid;
    padding: 25px 30px 25px 30px;
}

table {
  border-collapse: collapse;
  width: 100%;
  max-width: 1200px;
  margin: 0 auto;
  font-size: 14px;
  text-align: center;
}

th {
  background-color: #abd4c6;
  border: 1px solid #ddd;
  padding: 8px;
  text-transform: uppercase;
}

td {
  border: 1px solid #ddd;
  padding: 8px;
}


</style>



<div class="container">
  <div class="row">
    <div class="col-md-12">
        <p class="lead 1" style="text-align:left">My Requests</p>





<table>

          <tr>

              

              <th>Address</th>

              <th>Help Class</th>

              <th>Quantity Requested</th>

              <th>Created At</th>

              <th>Track Status</th>

              <th>Actions</th>

          </tr>

          {% for post in posts %}

              <tr id="hiderow">

                  

                  <td>{{ post.address }}</td>

                  <td>{{ post.help_class }}</td>

                  <td>

                      {{ post.original_quantity }}


                  </td>

                  <td>{{ post.created_at | prettydate }}</td>

                  <td>

                      {% if post.quantity == post.original_quantity %}

                          Request was received

                      {% elif post.quantity < post.original_quantity and post.quantity != 0 %}

                          Partially helped


                      {% else %}

                          {% if post.quantity == post.original_quantity %}

                              {% comment %} Set "help_completed" variable to true {% endcomment %}

                              {% with help_completed=True %}

                              {% endwith %}

                          {% endif %}

                          Help is completed

                      {% endif %}

                  </td>


                  <td>
                      {% if post.quantity < post.original_quantity %}

                             This request has been Partially/Fully helped, You cannot delete this request!
                      
                      {% else %}
                            <a class="btn btn-danger" href="{% url 'user:delete_request' pk=post.pk  %}" role="button">Delete </a>
                      {% endif %}

                  </td>

              </tr>

          {% endfor %}

      </table>
         {% if posts.has_other_pages %}
      <div class="pagination">
        <span class="step-links">
          {% if posts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ posts.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current-page">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
          </span>

          {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
            <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    {% endif %}

</div>
  </div>
</div>



{% endblock %}